### ISSUE TITLE
Error: No node found for selector: [tooltip-text="Videos"]

### ISSUE THREAD

**Issue by Ventrex** [vasani-arpit/Youtube-remove-copyright#5]
First of all, thank you for making this script.

I am working on Windows 10 and installed Chrome.
Then I installed GIT with NPM, like descriped in the readme.

But when I start "node index.js" I first see chrome, in my command prompt I see some text in multiple colors (green,blue,white,yellow)
So it all looks good. But when my page is fully loaded I get the following error, is this normal? 

Error: No node found for selector: [tooltip-text="Videos"]
    at assert (<Folder with index.js>\node_modules\puppeteer-core\lib\helper.js:283:11)
    at DOMWorld.click (<Folder with index.js>\node_modules\puppeteer-core\lib\DOMWorld.js:366:5)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async openTab (<Folder with index.js>\utils\tab.js:5:9)
    at async launch (<Folder with index.js>\index.js:31:20)
  -- ASYNC --
    at Frame.<anonymous> (<Folder with index.js>\node_modules\puppeteer-core\lib\helper.js:111:15)
    at Page.click (<Folder with index.js>\node_modules\puppeteer-core\lib\Page.js:1064:29)
    at openTab (<Folder with index.js>\utils\tab.js:5:20)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async launch (<Folder with index.js>\index.js:31:20)

**Comment by vasani-arpit** [comment]
This is not normal. I think youtube might have changed the HTML structure of the list page. I don't have time and test videos to debug this in my local machine as you have the script running I can join in over the call today or tomorrow and check this on your machine here https://calendar.x.ai/arpitvasani/

Either code might be outdated or youtube may have changed things. Let's see how big the change is if it is small then we will do it right away.

**Comment by Ventrex** [comment]
Sorry for the late reply. But if this is a common issue I might check if I can fix it myself by using Powershell. 
If I get that script working I will send it to you ;-)
